#################################################################
# File        : zen_blue_client.py
# Original    : Segment_and_and_Cutout_Masks.py
# Version     : 0.1
# Institution : Carl Zeiss Microscopy GmbH
#
# Copyright(c) 2019 Carl Zeiss AG, Germany. All Rights Reserved.
#
# Permission is granted to use, modify and distribute this code,
# as long as this copyright notice remains part of the code.
#################################################################
"""
zen_blue_client.py — ZEISS ZEN Blue TCP/IP client macro.

This IronPython macro runs directly inside ZEISS ZEN Blue through the
OAD environment. It acts as the microscope-side client of the Smart
Microscopy Image Denoising workflow.

The macro can process either:

    1. A CZI image that is already open in ZEN Blue.
    2. A newly acquired CZI image generated by a predefined ZEN
       experiment.

For each image, the macro:

    1. Saves the multichannel CZI image locally.
    2. Opens a TCP/IP connection to the Linux μPiX server.
    3. Sends the complete CZI file.
    4. Receives the number of denoised outputs announced by the server.
    5. Receives each processed CZI file.
    6. Loads and displays each returned result directly in ZEN Blue.

This script must be executed from the ZEN Blue macro editor and not from
a standard Python interpreter because it depends on ZEN and .NET objects
provided by the ZEN OAD runtime.
"""

import System
from System.Net.Sockets import TcpClient
import System.Net.IPAddress as IPA
from System.IO import File, Path
from System.Text import Encoding
import System.BitConverter as BC
import sys
import os
from System.Windows.Forms import (
    MessageBox,
    MessageBoxButtons,
    MessageBoxIcon,
)


# ----------------------------------------------------------
# VALIDATED LASER INTENSITY INFORMATION
# ----------------------------------------------------------

# These values correspond to the minimum laser intensities used during
# μPiX model validation for each wavelength. Below these values, reliable
# restoration is not guaranteed by the validation performed during the
# project.
message = (
    "Accepted Laser Intensity & Wavelength\n"
    "\t\t-----------------\n"
    "\t\t3.0%    |    488\n"
    "\t\t-----------------\n"
    "\t\t1.3%    |    561\n"
    "\t\t-----------------\n"
    "\t\t0.7%    |    640\n"
    "\t\t-----------------"
)

caption = "Information"

MessageBox.Show(
    message,
    caption,
)


# ----------------------------------------------------------
# ZEN AND NETWORK CONFIGURATION
# ----------------------------------------------------------

# Replace these generic values with the configuration of your ZEN workstation.
EXP_NAME = "ZEISS - LSM"

SAVE_PATH = r"C:\path\to\temporary"
SAVE_DIR = r"C:\path\to\results"

SERVER_IP = "SERVER_IP_ADDRESS"
SERVER_PORT = 5000

CZIfiles_short = []
CZIdict = {}


# ----------------------------------------------------------
# ZEN DOCUMENT DISCOVERY
# ----------------------------------------------------------

# Clear the ZEN macro console before starting a new run.
Zen.Application.MacroEditor.ClearMessages()

# List CZI documents currently open in ZEN Blue. These entries are used
# only by manual mode. Automatic mode creates a new image directly from
# the configured ZEN experiment.
open_documents = Zen.Application.Documents

for document in open_documents:
    image = Zen.Application.Documents.GetByName(
        document.Name
    )

    if image.FileName.EndsWith(".czi"):
        short_name = Path.GetFileName(
            image.FileName
        )

        CZIfiles_short.append(
            short_name
        )

        CZIdict[short_name] = image.FileName


# ----------------------------------------------------------
# MODE SELECTION WINDOW
# ----------------------------------------------------------

MODE_MANUAL = "Manual - Process an image already open in ZEN"
MODE_AUTO = "Automatic - Start a new acquisition"

window = ZenWindow()
window.Initialize(
    "Denoising of a 3-Channel Image using μPiX"
)

window.AddLabel(
    "Select the processing mode:"
)

window.AddDropDown(
    "mode",
    "Processing mode",
    [
        MODE_MANUAL,
        MODE_AUTO,
    ],
    0,
)

window.AddLabel(
    "For manual mode, select the CZI image to process:"
)

window.AddDropDown(
    "czi",
    "Select CZI Image Document",
    CZIfiles_short,
    0,
)

result = window.Show()

if result.HasCanceled == True:
    sys.exit(
        "Macro aborted by user."
    )

mode = result.GetValue(
    "mode"
)


# ----------------------------------------------------------
# LOCAL WORKING DIRECTORIES
# ----------------------------------------------------------

# Create the local input/output folders if they do not already exist.
if not os.path.exists(SAVE_DIR):
    os.makedirs(SAVE_DIR)

if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)


# ----------------------------------------------------------
# IMAGE ACQUISITION OR SELECTION
# ----------------------------------------------------------

if mode == MODE_AUTO:

    # ------------------------------------------------------
    # AUTOMATIC MODE
    # ------------------------------------------------------
    # Run the predefined ZEN experiment. The acquisition settings
    # (laser power, gain, Z-stack, etc.) are defined in ZEN Experiment
    # Designer and are therefore not duplicated in this macro.

    print(
        "[EXPERIMENT] Starting automatic acquisition: %s"
        % EXP_NAME
    )

    try:
        experiment = Zen.Acquisition.Experiments.GetByName(
            EXP_NAME
        )

        img = Zen.Acquisition.Execute(
            experiment
        )

    except Exception as exc:
        MessageBox.Show(
            "Unable to execute experiment '%s': %s"
            % (
                EXP_NAME,
                str(exc),
            ),
            "Acquisition Error",
            MessageBoxButtons.OK,
            MessageBoxIcon.Error,
        )

        sys.exit(
            "Macro aborted: experiment execution failed."
        )

    print(
        "[EXPERIMENT] Acquisition completed. "
        "Image retrieved from ZEN."
    )

else:

    # ------------------------------------------------------
    # MANUAL MODE
    # ------------------------------------------------------
    # Use a CZI image that is already open in the ZEN Blue document
    # workspace.

    czi_name = result.GetValue(
        "czi"
    )

    img = Zen.Application.Documents.GetByName(
        czi_name
    )

    Zen.Application.Documents.ActiveDocument = img


# ----------------------------------------------------------
# NETWORK FUNCTIONS
# ----------------------------------------------------------

def recv_exact(stream, n):
    """Receive exactly ``n`` bytes from a .NET NetworkStream.

    ``NetworkStream.Read()`` may return fewer bytes than requested. This
    helper therefore keeps reading until the expected amount has been
    received.

    Args:
        stream (System.Net.Sockets.NetworkStream): Active TCP stream.
        n (int): Number of bytes to receive.

    Returns:
        str: A string containing exactly ``n`` byte values.

    Raises:
        Exception: If the server closes the connection before all bytes
            are received.
    """
    data = []

    while len(data) < n:
        needed = n - len(data)

        buffer = System.Array.CreateInstance(
            System.Byte,
            needed,
        )

        bytes_read = stream.Read(
            buffer,
            0,
            needed,
        )

        if bytes_read == 0:
            raise Exception(
                "The server closed the connection."
            )

        for index in range(bytes_read):
            data.append(
                buffer[index]
            )

    return "".join(
        map(
            chr,
            data,
        )
    )


def receive_file(stream):
    """Receive one processed CZI file from the Linux μPiX server.

    The file uses the same header structure as the Python TCP clients:

        1. Filename length: 4-byte integer, big-endian.
        2. UTF-8 encoded filename.
        3. File size: 8-byte integer, big-endian.
        4. Raw file content.

    Args:
        stream (System.Net.Sockets.NetworkStream): Active TCP stream.

    Returns:
        tuple[str, str]: Local path of the saved result and filename.

    Raises:
        Exception: If the TCP connection is interrupted during reception.
    """

    # Read the 4-byte filename length.
    name_size_bytes = recv_exact(
        stream,
        4,
    )

    name_size_array = System.Array.CreateInstance(
        System.Byte,
        4,
    )

    for index in range(4):
        name_size_array[index] = ord(
            name_size_bytes[index]
        )

    name_size = IPA.NetworkToHostOrder(
        BC.ToInt32(
            name_size_array,
            0,
        )
    )

    # Read the UTF-8 filename.
    filename = recv_exact(
        stream,
        name_size,
    )

    filename = os.path.basename(
        filename
    )

    # Read the 8-byte file size.
    file_size_bytes = recv_exact(
        stream,
        8,
    )

    file_size_array = System.Array.CreateInstance(
        System.Byte,
        8,
    )

    for index in range(8):
        file_size_array[index] = ord(
            file_size_bytes[index]
        )

    file_size = IPA.NetworkToHostOrder(
        BC.ToInt64(
            file_size_array,
            0,
        )
    )

    print(
        "[RETURN] Receiving file: %s (%d bytes)"
        % (
            filename,
            file_size,
        )
    )

    # Stream the returned file directly to disk.
    result_path = os.path.join(
        SAVE_DIR,
        filename,
    )

    file_stream = System.IO.File.Create(
        result_path
    )

    try:
        received = 0
        chunk_size = 4096

        while received < file_size:
            needed = min(
                chunk_size,
                file_size - received,
            )

            buffer = System.Array.CreateInstance(
                System.Byte,
                needed,
            )

            bytes_read = stream.Read(
                buffer,
                0,
                needed,
            )

            if bytes_read == 0:
                raise Exception(
                    "The connection was closed while receiving the file."
                )

            file_stream.Write(
                buffer,
                0,
                bytes_read,
            )

            received += bytes_read

        print(
            "[RETURN] File saved successfully: %s"
            % result_path
        )

    finally:
        file_stream.Close()

    return result_path, filename


# ----------------------------------------------------------
# STEP 1: SAVE THE IMAGE LOCALLY
# ----------------------------------------------------------

# Whether the image comes from manual mode or from a new automatic
# acquisition, save it to disk first so that it can be transferred as
# raw bytes over TCP/IP.

base_name = (
    img.Name
    if img.Name.lower().endswith(".czi")
    else img.Name + ".czi"
)

save_file = os.path.join(
    SAVE_PATH,
    base_name,
)

img.Save(
    save_file
)

print(
    "[ZEN] Raw multichannel image saved locally: %s"
    % save_file
)


# ----------------------------------------------------------
# STEP 2: SEND THE IMAGE AND RECEIVE PROCESSED RESULTS
# ----------------------------------------------------------

print(
    "\n" + "=" * 60
)

print(
    "  TCP/IP μPiX PROCESSING — ZEISS ZEN BLUE CLIENT"
)

print(
    "=" * 60
)

try:

    # Prepare global image transfer metadata.
    filename = os.path.basename(
        save_file
    )

    filename_bytes = Encoding.UTF8.GetBytes(
        filename
    )

    name_size = filename_bytes.Length

    # Read the complete CZI file as bytes for transfer.
    img_bytes = File.ReadAllBytes(
        save_file
    )

    file_size = img_bytes.Length

    print(
        "[CONNECTION] Connecting to Linux server %s:%d..."
        % (
            SERVER_IP,
            SERVER_PORT,
        )
    )

    client = TcpClient(
        SERVER_IP,
        SERVER_PORT,
    )

    stream = client.GetStream()

    print(
        "[CONNECTION] Connected."
    )

    # ------------------------------------------------------
    # SEND THE COMPLETE MULTICHANNEL CZI FILE
    # ------------------------------------------------------

    print(
        "[SEND] Sending multichannel image... (%d bytes)"
        % file_size
    )

    # Send filename length.
    name_size_bytes = BC.GetBytes(
        IPA.HostToNetworkOrder(
            name_size
        )
    )

    stream.Write(
        name_size_bytes,
        0,
        4,
    )

    # Send filename.
    stream.Write(
        filename_bytes,
        0,
        name_size,
    )

    # Send file size.
    file_size_bytes = BC.GetBytes(
        IPA.HostToNetworkOrder(
            long(file_size)
        )
    )

    stream.Write(
        file_size_bytes,
        0,
        8,
    )

    # Send file content in 4096-byte chunks.
    CHUNK_SIZE = 4096
    offset = 0

    while offset < file_size:
        length = min(
            CHUNK_SIZE,
            file_size - offset,
        )

        stream.Write(
            img_bytes,
            offset,
            length,
        )

        offset += length

    stream.Flush()

    print(
        "[SEND] Image sent. Waiting for Linux processing..."
    )

    # ------------------------------------------------------
    # RECEIVE THE DYNAMIC OUTPUT COUNT
    # ------------------------------------------------------

    # The server announces how many processed CZI files will follow.
    num_files_bytes = recv_exact(
        stream,
        4,
    )

    num_files_array = System.Array.CreateInstance(
        System.Byte,
        4,
    )

    for index in range(4):
        num_files_array[index] = ord(
            num_files_bytes[index]
        )

    num_outputs = IPA.NetworkToHostOrder(
        BC.ToInt32(
            num_files_array,
            0,
        )
    )

    print(
        "[RETURN] Server announced %d processed volume(s)."
        % num_outputs
    )

    # ------------------------------------------------------
    # RECEIVE AND DISPLAY ALL PROCESSED CZI FILES
    # ------------------------------------------------------

    for index in range(num_outputs):
        print(
            "\n--- Processed volume %d/%d ---"
            % (
                index + 1,
                num_outputs,
            )
        )

        predicted_file_path, returned_filename = receive_file(
            stream
        )

        # Load each result and immediately display it in ZEN Blue.
        predicted_image = Zen.Application.LoadImage(
            predicted_file_path
        )

        Zen.Application.Documents.Add(
            predicted_image
        )

        print(
            "[ZEN] Processed volume displayed in ZEN Blue."
        )

    stream.Close()
    client.Close()

    print(
        "\n[CONNECTION] Closed cleanly. Processing completed."
    )

except Exception as exc:
    print(
        "[ERROR] Processing failed: %s"
        % str(exc)
    )
